trueFr = [[2];[3]];
delta = 0.05;


%% Поиск моментов попадания в трубку для каждого чистого сигнала
eigsType = ["NE"; "BU"];
tsettlingNE= transTime(delta, trueFr, eigsType(1));
tsettlingBU= transTime(delta, trueFr, eigsType(2));
mods = ["pure" "noise" "sinus" "change"];
mus = [1 25 5 10];
size = ".mat";

%% Здесь подгружаются сигналы с шумами и создаются выборки 
selectionsNE = cell(1,3);
selectionsBU = cell(1,3);

for i = 1:3
    selectionsNE{i} = selectionToCheck(mods(i+1)+eigsType(1)+mus(1)+size,...
        mods(i+1)+eigsType(1)+mus(2)+size, mods(i+1)+eigsType(1)+mus(3)+size,...
        mods(i+1)+eigsType(1)+mus(4)+size, tsettlingNE);
    selectionsBU{i} = selectionToCheck(mods(i+1)+eigsType(2)+mus(1)+size,...
        mods(i+1)+eigsType(2)+mus(2)+size, mods(i+1)+eigsType(2)+mus(3)+size,...
        mods(i+1)+eigsType(2)+mus(4)+size, tsettlingBU);
end

%% рассчёт RMSE
tempor = selectionsNE{1}{1}(1,:);
rmseNEnoisy = [...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{1}{1}(1,:))] ),selectionsNE{1}{1}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{1}{1}(2,:))] ),selectionsNE{1}{1}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{1}{2}(1,:))] ),selectionsNE{1}{2}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{1}{2}(2,:))] ),selectionsNE{1}{2}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{1}{3}(1,:))] ),selectionsNE{1}{3}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{1}{3}(2,:))] ),selectionsNE{1}{3}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{1}{4}(1,:))] ),selectionsNE{1}{4}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{1}{4}(2,:))] ),selectionsNE{1}{4}(2,:)))...
    ];


rmseNEsin = [...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{2}{1}(1,:))] ),selectionsNE{2}{1}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{2}{1}(2,:))] ),selectionsNE{2}{1}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{2}{2}(1,:))] ),selectionsNE{2}{2}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{2}{2}(2,:))] ),selectionsNE{2}{2}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{2}{3}(1,:))] ),selectionsNE{2}{3}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{2}{3}(2,:))] ),selectionsNE{2}{3}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{2}{4}(1,:))] ),selectionsNE{2}{4}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{2}{4}(2,:))] ),selectionsNE{2}{4}(2,:)))...
    ];

rmseNEChange = [...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{3}{1}(1,:))] ),selectionsNE{3}{1}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{3}{1}(2,:))] ),selectionsNE{3}{1}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{3}{2}(1,:))] ),selectionsNE{3}{2}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{3}{2}(2,:))] ),selectionsNE{3}{2}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{3}{3}(1,:))] ),selectionsNE{3}{3}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{3}{3}(2,:))] ),selectionsNE{3}{3}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsNE{3}{4}(1,:))] ),selectionsNE{3}{4}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsNE{3}{4}(2,:))] ),selectionsNE{3}{4}(2,:)))...
    ];



rmseBUnoisy = [...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{1}{1}(1,:))] ),selectionsBU{1}{1}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{1}{1}(2,:))] ),selectionsBU{1}{1}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{1}{2}(1,:))] ),selectionsBU{1}{2}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{1}{2}(2,:))] ),selectionsBU{1}{2}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{1}{3}(1,:))] ),selectionsBU{1}{3}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{1}{3}(2,:))] ),selectionsBU{1}{3}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{1}{4}(1,:))] ),selectionsBU{1}{4}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{1}{4}(2,:))] ),selectionsBU{1}{4}(2,:)))...
    ];


rmseBUsin = [...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{2}{1}(1,:))] ),selectionsBU{2}{1}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{2}{1}(2,:))] ),selectionsBU{2}{1}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{2}{2}(1,:))] ),selectionsBU{2}{2}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{2}{2}(2,:))] ),selectionsBU{2}{2}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{2}{3}(1,:))] ),selectionsBU{2}{3}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{2}{3}(2,:))] ),selectionsBU{2}{3}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{2}{4}(1,:))] ),selectionsBU{2}{4}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{2}{4}(2,:))] ),selectionsBU{2}{4}(2,:)))...
    ];

rmseBUChange = [...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{3}{1}(1,:))] ),selectionsBU{3}{1}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{3}{1}(2,:))] ),selectionsBU{3}{1}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{3}{2}(1,:))] ),selectionsBU{3}{2}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{3}{2}(2,:))] ),selectionsBU{3}{2}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{3}{3}(1,:))] ),selectionsBU{3}{3}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{3}{3}(2,:))] ),selectionsBU{3}{3}(2,:)));...
    sqrt(immse(imresize(trueFr(1),[1 length(selectionsBU{3}{4}(1,:))] ),selectionsBU{3}{4}(1,:)))...
    sqrt(immse(imresize(trueFr(2),[1 length(selectionsBU{3}{4}(2,:))] ),selectionsBU{3}{4}(2,:)))...
    ];


changeMid = zeros(2,4);
noiseMid = zeros(2,4);
sinMid = zeros(2,4);

    for j=1:4
        changeMid(1,j) = sqrt(rmseNEChange(j,1)^2 + rmseNEChange(j,2)^2);
        noiseMid(1,j) = sqrt(rmseNEnoisy(j,1)^2 + rmseNEnoisy(j,2)^2);
        sinMid(1,j) = sqrt(rmseNEsin(j,1)^2 + rmseNEsin(j,2)^2);
        changeMid(2,j) = sqrt(rmseBUChange(j,1)^2 + rmseBUChange(j,2)^2);
        noiseMid(2,j) = sqrt(rmseBUnoisy(j,1)^2 + rmseBUnoisy(j,2)^2);
        sinMid(2,j) = sqrt(rmseBUnoisy(j,1)^2 + rmseBUnoisy(j,2)^2);
    end

save('rmseValues', "rmseBUChange", "rmseBUnoisy", "rmseBUsin", "rmseNEChange", "rmseNEnoisy", "rmseNEsin");
 
mods = ["PURE" "NOISE" "SIN" "CHANGE"];

load('PUREVED.mat');
time = approx_data(1,:);
fr1 = approx_data(2,:);
fr2 = approx_data(3,:);
   
idx1 = find(abs(fr1 - trueFr(1)) > delta*trueFr(1));
idx2 = find(abs(fr2 - trueFr(2)) > delta*trueFr(1));
tsettlingNEF = ceil(time(max(idx1(end),idx2(end)))) *10000;

tsettling = cell(1,3);

tsettling{1,1} = tsettlingNE;
tsettling{1,2} = tsettlingBU;
tsettling{1,3} = tsettlingNEF;
midMRSEs = zeros(3,3);
eigsType = ["NE" "BU"];
for i = 1:3
    for j = 1:2
        load(mods(i)+mus(2)+eigsType(j)+size);
        fr1 = approx_data(2,:);
        fr2 = approx_data(3,:);
        settle = [fr1(tsettling{j}(2):end);fr2(tsettling{j}(2):end)];
        rerr1 = sqrt(immse(imresize(trueFr(1),[1 length(settle(1,:))] ),settle(1,:)));
        rerr2 = sqrt(immse(imresize(trueFr(2),[1 length(settle(2,:))] ),settle(2,:)));
        midMRSEs(i,j) = sqrt(rerr1^2 + rerr2^2);
    end

    load(mods(i+1)+"VED"+size);
    fr1 = approx_data(2,:);
    fr2 = approx_data(3,:);
    settle = [fr1(tsettling{3}(1):end);fr2(tsettling{3}(1):end)];
    rerr1 = sqrt(immse(imresize(trueFr(1),[1 length(settle(1,:))] ),settle(1,:)));
    rerr2 = sqrt(immse(imresize(trueFr(2),[1 length(settle(2,:))] ),settle(2,:)));
    midMRSEs(i,3) = sqrt(rerr1^2 + rerr2^2);
end


  